<a href="https://colab.research.google.com/github/Pablz1924/ObesidadML/blob/main/Perceptron_obesidad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Red Neuronal Artificial: PERCEPTRÓN**
```
Autor     : Pabel Sebastian Peña Tejada
Problema  : Obesidad.
```

# **1. IMPORTACIÓN DE LIBRERÍAS**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random
import math

from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# **2. IMPORTACIÓN DE DATOS**

In [ ]:
datos = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv", sep=',')
datos.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

# **3. PREPARACIÓN DE DATOS**

# Determinar si existen datos faltantes

In [ ]:
# visualizar información del dataset
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [ ]:
#número de valores nulos por cada atributo
datos.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [ ]:
# Visualizar datos imputados utilizando la media
datos.head()

Gender   Age  Height  Weight family_history_with_overweight FAVC  FCVC  \
0  Female  21.0    1.62    64.0                            yes   no   2.0   
1  Female  21.0    1.52    56.0                            yes   no   3.0   
2    Male  23.0    1.80    77.0                            yes   no   2.0   
3    Male  27.0    1.80    87.0                             no   no   3.0   
4    Male  22.0    1.78    89.8                             no   no   2.0   

   NCP       CAEC SMOKE  CH2O  SCC  FAF  TUE        CALC  \
0  3.0  Sometimes    no   2.0   no  0.0  1.0          no   
1  3.0  Sometimes   yes   3.0  yes  3.0  0.0   Sometimes   
2  3.0  Sometimes    no   2.0   no  2.0  1.0  Frequently   
3  3.0  Sometimes    no   2.0   no  2.0  0.0  Frequently   
4  1.0  Sometimes    no   2.0   no  0.0  0.0   Sometimes   

                  MTRANS           NObeyesdad  
0  Public_Transportation        Normal_Weight  
1  Public_Transportation        Normal_Weight  
2  Public_Transportation        Normal_Weight  
3                Walking   Overweight_Level_I  
4  Public_Transportation  Overweight_Level_II

# Conversión de datos Categóricos a Numéricos

In [ ]:
# Implementación de un módulo que convierte un atributo categórico a numérico
def Categorico_a_numerico(atributo):
    # Convertir el atributo al tipo categórico
    atributo = atributo.astype("category")
    # Convertir el atributo categórico a numérico
    return atributo.astype("category").cat.codes

In [ ]:
# convertir los categóricos a numéricos
# datos['EJEMPLO'] = Categorico_a_numerico(datos['EJEMPLO'])
datos['Gender']=Categorico_a_numerico(datos['Gender'])
datos['family_history_with_overweight']=Categorico_a_numerico(datos['family_history_with_overweight'])
datos['FAVC']=Categorico_a_numerico(datos['FAVC'])
datos['CAEC']=Categorico_a_numerico(datos['CAEC'])
datos['SMOKE']=Categorico_a_numerico(datos['SMOKE'])
datos['SCC']=Categorico_a_numerico(datos['SCC'])
datos['CALC']=Categorico_a_numerico(datos['CALC'])
datos['MTRANS']=Categorico_a_numerico(datos['MTRANS'])
datos['NObeyesdad']=Categorico_a_numerico(datos['NObeyesdad'])
# En este caso, no se tiene ningún datos categórico
datos.head()

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6

# Implementar la normalización de datos por amplitud

In [ ]:
# Transformación por amplitud [0..1]
def Normalizacion_Amplitud(atributo):
    return (atributo - atributo.min())/(atributo.max() - atributo.min())

In [ ]:
# Datos antes de la normalizacion por amplitud
datos.head()

Gender   Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0       0  21.0    1.62    64.0                               1     0   2.0   
1       0  21.0    1.52    56.0                               1     0   3.0   
2       1  23.0    1.80    77.0                               1     0   2.0   
3       1  27.0    1.80    87.0                               0     0   3.0   
4       1  22.0    1.78    89.8                               0     0   2.0   

   NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  NObeyesdad  
0  3.0     2      0   2.0    0  0.0  1.0     3       3           1  
1  3.0     2      1   3.0    1  3.0  0.0     2       3           1  
2  3.0     2      0   2.0    0  2.0  1.0     1       3           1  
3  3.0     2      0   2.0    0  2.0  0.0     1       4           5  
4  1.0     2      0   2.0    0  0.0  0.0     2       3           6

In [ ]:
datos.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [ ]:
datos['Gender'] = Normalizacion_Amplitud(datos['Gender'])
datos['Age'] = Normalizacion_Amplitud(datos['Age'])
datos['Height'] = Normalizacion_Amplitud(datos['Height'])
datos['Weight'] = Normalizacion_Amplitud(datos['Weight'])
datos['family_history_with_overweight'] = Normalizacion_Amplitud(datos['family_history_with_overweight'])
datos['FAVC'] = Normalizacion_Amplitud(datos['FAVC'])
datos['FCVC'] = Normalizacion_Amplitud(datos['FCVC'])
datos['NCP'] = Normalizacion_Amplitud(datos['NCP'])
datos['CAEC'] = Normalizacion_Amplitud(datos['CAEC'])
datos['SMOKE'] = Normalizacion_Amplitud(datos['SMOKE'])
datos['CH2O'] = Normalizacion_Amplitud(datos['CH2O'])
datos['SCC'] = Normalizacion_Amplitud(datos['SCC'])
datos['FAF'] = Normalizacion_Amplitud(datos['FAF'])
datos['TUE'] = Normalizacion_Amplitud(datos['TUE'])
datos['CALC'] = Normalizacion_Amplitud(datos['CALC'])
datos['MTRANS'] = Normalizacion_Amplitud(datos['MTRANS'])


In [ ]:
# Datos después de la normalizacion por amplitud
datos.head()

Gender       Age    Height    Weight  family_history_with_overweight  FAVC  \
0     0.0  0.148936  0.320755  0.186567                             1.0   0.0   
1     0.0  0.148936  0.132075  0.126866                             1.0   0.0   
2     1.0  0.191489  0.660377  0.283582                             1.0   0.0   
3     1.0  0.276596  0.660377  0.358209                             0.0   0.0   
4     1.0  0.170213  0.622642  0.379104                             0.0   0.0   

   FCVC       NCP      CAEC  SMOKE  CH2O  SCC       FAF  TUE      CALC  \
0   0.5  0.666667  0.666667    0.0   0.5  0.0  0.000000  0.5  1.000000   
1   1.0  0.666667  0.666667    1.0   1.0  1.0  1.000000  0.0  0.666667   
2   0.5  0.666667  0.666667    0.0   0.5  0.0  0.666667  0.5  0.333333   
3   1.0  0.666667  0.666667    0.0   0.5  0.0  0.666667  0.0  0.333333   
4   0.5  0.000000  0.666667    0.0   0.5  0.0  0.000000  0.0  0.666667   

   MTRANS  NObeyesdad  
0    0.75           1  
1    0.75           1  
2    0.75           1  
3    1.00           5  
4    0.75           6

In [ ]:
datos.shape

(2111, 17)

# **4. SEPARADO DE DATOS**

In [ ]:
X = datos.drop('NObeyesdad', axis=1)  # Características
y = datos['NObeyesdad']  # Variable objetivo

In [ ]:
# División de los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

# **5. CONFIGURACIÓN DEL MODELO**

In [ ]:
modelo = MLPClassifier(hidden_layer_sizes = (100, 50),activation = 'relu',solver = 'adam'  ,alpha = 0.0001  ,max_iter = 200  ,learning_rate = 'constant')

# **6. ENTRENAR MODELO**

In [ ]:
modelo.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(100, 50))

# **7. TEST**

In [ ]:
y_pred = modelo.predict(X_test)

# **8. MATRIZ CONJUGADA**

In [ ]:
matriz_confusion = metrics.confusion_matrix(y_test, y_pred)
print('matriz de confusión\n', matriz_confusion)

matriz de confusión
 [[ 77   3   0   0   0   0   0]
 [  1  79   0   0   0   4   0]
 [  0   0 103   2   0   0   1]
 [  0   0   1  85   0   0   0]
 [  0   0   1   1  99   0   0]
 [  0   3   1   0   0  80   6]
 [  0   0   1   0   0   3  83]]


# **9. OBTENER MÉTRICAS**

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred)
precision = metrics.precision_score(y_test, y_pred, average='weighted')
recall = metrics.recall_score(y_test, y_pred, average='weighted')
f1_score = metrics.f1_score(y_test, y_pred, average='weighted')

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("f1", f1_score)

Accuracy:  0.9558359621451105
Precision:  0.9560606722845324
Recall:  0.9558359621451105
f1 0.9558135660820263


# **10. NUEVAS PREDICCIONES**

In [ ]:
import warnings

# Desactivar advertencias
warnings.filterwarnings("ignore", category=UserWarning)

nuevos_datos = [[1.0, 0.275, 0.400, 0.250, 0.0, 1.0, 0.6, 0.4, 0.2, 0.0, 0.8, 0.0, 0.25, 0.75, 0.5, 0.5]]

predicciones_nuevas = modelo.predict(nuevos_datos)
print(predicciones_nuevas)

[1]
